import type { Question } from '../../engine/types';

/**
 * Question bank — 34 units. short 10 ⊂ medium 20 ⊂ long 34.
 *
 * REWRITTEN 2026-08-28 after the craft review rejected the first bank. Five independent
 * readers ran the substitution test and all five reached the same verdict: it was
 * **costumed** — mundane dilemmas with wizarding nouns dropped in. Swap "experiment" back
 * for "potion", "text" for "owl", "manager" for "head of house", and every question was
 * unchanged. That is the worst of the card's four categories, worse than reading as
 * generic, and it happened for a specific reason worth recording: the linter's
 * `skinned-question` advisory measures too LITTLE world vocabulary, so it was satisfied by
 * sprinkling ALLOW-tier nouns into stems — which is precisely the noun-swapping the card
 * calls "worse than neutral". A rule that can be satisfied without doing the work will be.
 *
 * Every unit here is instead generated by one of the eight world-pressures in
 * `_craft/packs/harry-potter/vocabulary.md`. The test each had to pass: put the plain
 * real-world equivalent back, and the dilemma has to CHANGE.
 *
 * THREE INVARIANTS, all machine-checked (`npm run audit`, `question-lint.py`):
 *
 * 1. AMPLITUDE BY TIER. Short units hit hardest on their primary axis, long units finest.
 *    Stated as a hard band here previously (short ±70..90, medium ±50..70, long ±30..55) —
 *    but measured, star-wars sits outside that band in 10 of its 34 units, so the band was
 *    an aspiration and not a spec. What the audit enforces is the property the band was
 *    reaching for: median amplitude must fall from short to long. Its failure mode is a
 *    long tier less decisive than the short one.
 * 2. ARRAY ORDER IS GROUPED BY `section`, CONTIGUOUSLY. `sectionsForTier()` throws
 *    otherwise. Reordering also changes `questionSetHash` (src/lib/engine/share.ts) and
 *    invalidates every share link in the wild — reorder only with a migration.
 * 3. NO `sig` HINTS. The first bank used 27 of them to paper over a coverage gap, and 10
 *    named a character the option scored AGAINST. star-wars uses none. Coverage belongs in
 *    the option vectors, honestly, or in `desiredShare` — not in a thumb on the scale.
 *    `sig-polarity` in the audit now catches the failure either way.
 *
 * No unit names a house, a named character, or any DENY-tier noun, and none grants the
 * taker a house, a bloodline or a rare power — any of those collapses the 47-name roster.
 */

/** Terse builder. Option ids are positional a|b|c|d, so options never carry their own ids. */
const q = (
	id: string,
	tier: Question['tier'],
	primaryAxis: string,
	section: string,
	text: string,
	options: Array<[string, Question['options'][number]['v']]>
): Question => ({
	id,
	tier,
	primaryAxis,
	section,
	text,
	options: options.map(([t, v], i) => ({ id: 'abcd'[i], text: t, v }))
});

export const QUESTIONS: Question[] = [
	// ================================================================ METHOD (precept)
	q('name-in-the-register', 'short', 'precept', 'method', 'A first-year cauldron cracks on your watch, and the register keeps that mark on your name long after the room reopens.', [
		['Put your name in, and be done.', { precept: 85, candour: 35, temper: -20 }],
		['Wedge the door shut. Skip the register.', { precept: -85, defiance: 55, ambition: -15 }],
		['List it, no name attached.', { precept: 25, candour: -55, defiance: 20 }],
		['Walk the first-year to the caretaker instead, and explain.', { precept: -20, attachment: 45, candour: 30, defiance: -35 }]
	]),
	q('nobody-of-age', 'short', 'precept', 'method', 'The banister is being mended the way your grandmother ordered it done years ago, by something that cannot take a new instruction from you.', [
		['Let it finish her way.', { precept: 85, defiance: -45, attachment: -20 }],
		['Work beside it and fix the parts it will not.', { precept: -50, attachment: 55, candour: -20 }],
		['Send for somebody whose order it will take.', { precept: 75, defiance: -30, ambition: -25 }],
		['Undo its work tonight, after it has gone.', { precept: -80, candour: -55, temper: 30 }]
	]),
	q('the-curfew-charm', 'medium', 'precept', 'method', 'Nobody has shown you how to set the curfew charm, but the portrait by the gate has watched it done right for two hundred years.', [
		['Ask the portrait to walk you through it.', { precept: 65, candour: -20, ambition: -10, defiance: -35 }],
		['Guess, and set it yourself.', { precept: -60, temper: 25, ambition: 15 }],
		['Copy what you did last time.', { precept: -30, candour: -15, ambition: -20 }],
		['Leave it, and report it undone by morning.', { precept: 40, candour: 40, ambition: -35 }]
	]),
	q('the-only-slot', 'long', 'precept', 'method', 'You swore to try the spell only under supervision, and the oath does not wait to see whether anyone is watching. Your last supervised hour is gone.', [
		['Sit it unrehearsed.', { precept: 50, ambition: -30, temper: -20 }],
		['Trade favours for a supervised hour that is not yours.', { precept: 35, attachment: 35, candour: -25 }],
		['Break the oath, and take the toll when it comes due.', { precept: -50, defiance: 45, temper: 25 }],
		['Request release before you break it.', { precept: 30, candour: 55, defiance: -25 }]
	]),
	q('wont-turn-the-key', 'long', 'precept', 'method', 'The oath you swore to keep the greenhouse locked after dark will not let your hand turn the key, and there is smoke already two rows in.', [
		['Blast the door open.', { precept: -50, temper: 40, defiance: 25 }],
		['Send the nearest first-year for the groundskeeper.', { precept: 50, attachment: -30, ambition: -20, defiance: -40 }],
		['Work the lock by hand instead.', { precept: -35, temper: -30, ambition: -25 }],
		['Get everyone out through the back, and leave it shut.', { precept: 35, attachment: 45, defiance: -25 }]
	]),

	// ================================================================ DISCLOSURE (candour)
	q('ledger-before-service', 'short', 'candour', 'disclosure', 'The apothecary opens the family ledger at his name, reads for a moment, and serves the rest of the queue before him.', [
		['Put it to the assistant, now, in front of the queue.', { candour: 85, temper: 45, defiance: 30, reckoning: 35 }],
		['Buy what you came for. Say nothing.', { candour: -85, attachment: -30, reckoning: -20 }],
		['Tell them: him first.', { candour: 75, precept: 20, attachment: 40 }],
		['Leave. Both of you, without a word.', { candour: -70, attachment: 55, defiance: 35, reckoning: -30 }]
	]),
	q('post-by-surname', 'medium', 'candour', 'disclosure', 'The post clerk sorts the tray by surname before opening it, and the exam pass your friend needs is still in the bag at five to nine.', [
		['Tell the clerk to open the bag, now.', { candour: 65, defiance: 35, temper: 20 }],
		['Get him in some other way, and say why later.', { candour: -55, attachment: 50, precept: -25 }],
		['Take it to a prefect, and say what is happening.', { candour: 60, precept: 40, attachment: 20, defiance: -35 }],
		['Wait for the bag. Tell him once it is over.', { candour: -65, attachment: -30, reckoning: -20 }]
	]),
	q('on-the-record', 'medium', 'candour', 'disclosure', 'The headmaster wants your account on the record, and whatever you say tonight stays in the register long after you have left.', [
		['State it exactly as it happened.', { candour: 68, precept: 45, defiance: -35, ambition: -20 }],
		['Give the version that leaves the least in the register.', { candour: -55, precept: 20, defiance: 20, temper: -25 }],
		['Answer only what you are made to.', { candour: -68, defiance: 45, precept: -40, temper: 30 }],
		['Tell a friend the whole of it. Keep the register thin.', { candour: 52, attachment: 45, precept: -35, defiance: 25 }]
	]),
	q('printed-by-dawn', 'long', 'candour', 'disclosure', 'The ministry has the newspaper printing its account by dawn, and it will not match what you watched happen from the gallery.', [
		['Write down what happened and send it before dawn.', { candour: 52, defiance: 35, precept: -25, ambition: 20 }],
		['Wait to be asked. Answer only that.', { candour: -32, defiance: -40, precept: 30, reckoning: -20 }],
		['Send it to somebody who is not the newspaper.', { candour: 30, attachment: 45, precept: -20, defiance: 20 }],
		['Say nothing. Let the account stand.', { candour: -55, reckoning: -35, ambition: -45, attachment: -20 }]
	]),
	q('portrait-was-asked', 'long', 'candour', 'disclosure', 'The portrait outside the library has watched you go the same way every night this term, and today it was finally asked what it has seen.', [
		['Ask it first, before they do.', { candour: -35, precept: -30, defiance: 25, temper: -20 }],
		['Go to them and say exactly where you have been.', { candour: 50, precept: 45, defiance: -35, attachment: 20 }],
		['Admit you were out. Leave the where alone.', { candour: -42, precept: 20, defiance: -20, ambition: -20 }],
		['Wait for the portrait, and confirm only what it says.', { candour: 32, precept: -20, defiance: -45, reckoning: -20 }]
	]),

	// ================================================================ ATTACHMENT
	q('sworn-to-skip', 'short', 'attachment', 'attachment', 'You could swear to skip the meeting for them or just say you will, and only the sworn word takes something out of you if it breaks.', [
		['Swear it, binding word.', { attachment: 85, precept: -40, ambition: -45 }],
		['Say you will. Leave it unsworn.', { attachment: 50, candour: 40, precept: 20 }],
		['Go to the meeting. Tell them you will not swear.', { attachment: -40, candour: 60, precept: 35 }],
		['Skip both. Swear nothing, show up nowhere.', { attachment: -75, candour: -55, temper: -30 }]
	]),
	q('moved-for-mending', 'short', 'attachment', 'attachment', 'Your dormitory is cleaned by something that takes no pay and would refuse it, and it is being moved to the kitchens for mending your things.', [
		['Speak for them, by name, to the headmaster.', { attachment: 85, candour: 55, defiance: 35, reckoning: 30 }],
		['Cover the rota yourself tonight, in their place.', { attachment: 60, precept: -30, ambition: -40 }],
		['Tell the kitchens you asked them to do it.', { attachment: 25, candour: -25, precept: 20 }],
		['Let the move happen. Say nothing.', { attachment: -80, candour: -50, temper: -30, reckoning: -30 }]
	]),
	q('off-the-registry', 'medium', 'attachment', 'attachment', 'The ministry runs the paper as well as the courts now, and whatever it prints about your closest friend by morning will stand without a hearing.', [
		['Reach your friend before morning.', { attachment: 65, defiance: 35, candour: 25 }],
		['Stay home, and let the paper print regardless.', { attachment: -60, temper: -25, precept: 30 }],
		['Bring a different account to the printer first.', { attachment: 55, candour: 50, defiance: 40 }],
		['Deny you know your friend at all.', { attachment: -65, candour: -40, reckoning: -20 }]
	]),
	q('oath-against-the-week', 'long', 'attachment', 'attachment', 'The oath you swore, sworn and not just promised, lands this week against the one thing you have wanted since you arrived.', [
		['Honour it.', { attachment: 55, ambition: -50, precept: 20 }],
		['Ask to be released from it first.', { attachment: -20, candour: 45, precept: 35, defiance: -30 }],
		['Split the week between them and hope it holds.', { attachment: 20, precept: -45, temper: 25 }],
		['Break it. Take what breaking it costs.', { attachment: -50, defiance: 40, temper: 30 }]
	]),
	q('told-it-was-them', 'long', 'attachment', 'attachment', 'Whoever tends the fires in your common room, unpaid, has told the caretaker it was their doing and not yours.', [
		['Let it stand as they told it.', { attachment: -50, candour: -45, reckoning: -20 }],
		['Go correct it yourself, right now.', { attachment: 45, candour: 55, precept: 20 }],
		['Thank them for it, quietly, and leave it be.', { attachment: 10, candour: -30, precept: -25 }],
		['Ask them first why they did it.', { attachment: 30, candour: 40, precept: -20 }]
	]),

	// ================================================================ AUTHORITY (defiance)
	q('two-years-off', 'short', 'defiance', 'authority', 'The tower door is jammed with somebody inside, and the charm that opens it fast is two years off being yours to use.', [
		['Say the charm and take the citation on your name.', { defiance: 85, candour: 55, precept: -40 }],
		['Pick the lock instead.', { defiance: -70, precept: 45, temper: -25 }],
		['Talk them through kicking it from the inside.', { defiance: -25, candour: 40, attachment: -35 }],
		['Run for a seventh-year and hand it to them.', { defiance: -85, ambition: -30, temper: -35 }]
	]),
	q('no-office-above-her', 'short', 'defiance', 'authority', 'Whatever your head of house writes tonight goes into the same book the ministry checks before it hires you, and there is no office above her to appeal to.', [
		['Say nothing, and let her write it from memory alone.', { defiance: 82, candour: -55, precept: -25 }],
		['Stop her, and hear the line before she signs it.', { defiance: 75, precept: 40, candour: 30 }],
		['Answer everything she asks, and stop there.', { defiance: -78, precept: 45, candour: 25 }],
		['Offer to make it right yourself, if she holds the line for now.', { defiance: -72, ambition: 40, candour: -35 }]
	]),
	q('the-portrait-on-the-landing', 'medium', 'defiance', 'authority', 'Your head of house wants the names from you now, but the portrait on the landing answers anyone who asks, and nobody has asked it yet.', [
		['Give him the names now, before he thinks to ask the portrait.', { defiance: -60, precept: 45, attachment: -30 }],
		['Warn the portrait first, and refuse him after.', { defiance: 55, attachment: 50, precept: -30 }],
		['Hold your silence, and let the portrait answer as it will.', { defiance: 65, precept: -20, temper: 20 }],
		['Tell him to ask the portrait himself.', { defiance: 55, candour: 40, precept: -25 }]
	]),
	q('whose-order-wins', 'long', 'defiance', 'authority', 'Something bound to your family was told to stop you leaving tonight, and one order from you undoes theirs. It will remember whose order won.', [
		['Order it to let you go, and go.', { defiance: 50, precept: -20, attachment: -15 }],
		['Ask what happens to it if you make it choose.', { defiance: -30, attachment: 55, candour: 40 }],
		['Go without ordering it. Leave it out of this.', { defiance: 40, attachment: 35, precept: -15 }],
		['Stay. Do not put it in the middle.', { defiance: -45, attachment: 45, ambition: -30 }]
	]),
	q('wards-on-the-pitch', 'long', 'defiance', 'authority', 'The flying instructor pulls you from the match: wards on the pitch logged you flying alone after your suspension began.', [
		['Sit out, and take the suspension as it stands.', { defiance: -50, precept: 40, ambition: -25 }],
		['Fly anyway. Let the wards log it twice.', { defiance: 50, temper: 30, precept: -35 }],
		['Ask to see exactly what the wards recorded.', { defiance: 30, candour: 40, precept: 20 }],
		['File a dispute that the wards logged the wrong flyer.', { defiance: 35, precept: 45, candour: -20 }]
	]),

	// ================================================================ RECKONING
	q('never-on-the-record', 'short', 'reckoning', 'reckoning', 'You were there last October and never put it on the record. They know that, and tonight they ask you for something before curfew.', [
		['Put it on the record tonight, before you answer.', { reckoning: 85, precept: 50, candour: 30 }],
		['Name your price, then answer them.', { reckoning: 50, ambition: 45, candour: -35 }],
		['Help them, and let it go for good.', { reckoning: -85, attachment: 40, candour: -30 }],
		['Say you remember it, and leave them wondering.', { reckoning: 15, temper: 30, precept: -25 }]
	]),
	q('the-ghost-on-the-staircase', 'medium', 'reckoning', 'reckoning', 'The ghost on the staircase tells the headmaster what happened the same way it tells anyone, and you are asked how hard the record should read.', [
		['Give it to them straight.', { reckoning: 65, candour: 50, precept: 30 }],
		['Leave out the part that makes it worse.', { reckoning: -60, candour: -55, attachment: 30 }],
		['Answer what is asked, and stop there.', { reckoning: 20, precept: 40, candour: -20, defiance: -35 }],
		['Ask that it wait until they can speak for themselves.', { reckoning: -45, defiance: 35, precept: -30 }]
	]),
	q('surname-that-blamed-him', 'medium', 'reckoning', 'reckoning', 'The boy whose surname got your friend blamed for something neither of them did is the one asking to borrow your notes tonight.', [
		['Lend him the notes.', { reckoning: -55, attachment: 30, candour: -20 }],
		['Make him ask in front of your friend.', { reckoning: 55, candour: 50, temper: 20 }],
		['Turn him down, and go back to your own notes.', { reckoning: 65, attachment: -35, candour: -30 }],
		['Hand them to your friend, and let him decide.', { reckoning: -50, attachment: 55, candour: -35 }]
	]),
	q('the-trace-that-went-unacted', 'long', 'reckoning', 'reckoning', 'The trace from what you did over the holidays reached the desk of the head of house anyway, and they are letting it go, this once.', [
		['Pocket it. Say nothing.', { reckoning: -40, precept: -30, ambition: 25 }],
		['Go back and thank them for it, plainly.', { reckoning: -25, candour: 45, attachment: 30 }],
		['Find out whether it happens again.', { reckoning: 15, defiance: -25, precept: 35 }],
		['Use the room again anyway. They did not say stop.', { reckoning: 45, defiance: 40, temper: 30 }]
	]),
	q('wont-take-your-word', 'long', 'reckoning', 'reckoning', 'Three generations of your family have been served against a debt nobody living remembers, and your word alone will not settle it.', [
		['Call the debt paid, and stop its work.', { reckoning: -45, attachment: 30, precept: -20 }],
		['Find the formal release it needs, and see it through.', { reckoning: -30, precept: 40, candour: -20, defiance: -35 }],
		['Give it one hard task, and close the debt after.', { reckoning: 50, temper: 25, ambition: 20 }],
		['Leave the debt where it stands, and keep it working.', { reckoning: 55, candour: -30, attachment: -25 }]
	]),

	// ================================================================ APPETITE (ambition)
	q('checked-against-the-register', 'short', 'ambition', 'appetite', 'The clerk checks your family against the register before you have said a word, and clears the queue for you.', [
		['Take the short queue. Say nothing.', { ambition: 85, candour: -55, precept: -30 }],
		['Stop them. Join the ordinary queue.', { ambition: -80, defiance: 40, precept: 35 }],
		['Ask what is written next to your name.', { ambition: 40, candour: 65, defiance: 30 }],
		['Put another name through the queue with yours.', { ambition: 55, attachment: 50, candour: -25 }]
	]),
	q('what-the-sorting-decided', 'medium', 'ambition', 'appetite', 'The careers adviser is going by what was decided about you at eleven, and has already started the form for the track it named.', [
		['Bend the track toward what you actually want.', { ambition: 65, precept: -35, candour: -20 }],
		['Press for the placement you actually want.', { ambition: 55, candour: 65, defiance: 30 }],
		['Leave the form unsigned for now.', { ambition: -35, precept: 20, temper: -30 }],
		['Take your name off every list they keep on you.', { ambition: -70, defiance: 55, attachment: -20 }]
	]),
	q('flagged-in-the-file', 'medium', 'ambition', 'appetite', 'Your father is flagged in the old inquiry file, and the editor wants to run your column under a different name instead.', [
		['Run the column under the other name.', { ambition: 70, candour: -65, precept: -25 }],
		['Hold out for your own name on it.', { ambition: 50, candour: 60, defiance: 45 }],
		['Turn it down, and send it where nobody asks.', { ambition: 55, defiance: 50, attachment: -25 }],
		['Find out what the file actually says about him.', { ambition: -30, candour: 40, precept: 30 }]
	]),
	q('the-plates-before-dawn', 'long', 'ambition', 'appetite', 'The results column credited another name for work that was yours, and the only correction on offer is a favour from whoever the ministry has signing the plates before dawn.', [
		['Ask for it yourself, and owe whoever signs the plates.', { ambition: 50, candour: 40, precept: -20 }],
		['Keep the proof yourself, and let the column stand as printed.', { ambition: -35, precept: 45, candour: -25 }],
		['Get the one credited to ask for the correction in your place.', { ambition: 40, attachment: 30, candour: -30 }],
		['Take it above the print office, and put your name to the complaint.', { ambition: 45, defiance: 45, candour: 50 }]
	]),
	q('already-down-for-it', 'long', 'ambition', 'appetite', 'The head of house mentions once that the seat vacated this morning always goes to a name already down for it, and moves on.', [
		['Ask outright whether your name is down for it.', { ambition: 45, candour: 55, defiance: 20 }],
		['Find the old holder. Ask them to put you forward.', { ambition: 40, attachment: 35, candour: -20 }],
		['Wait. Watch who asks first.', { ambition: -30, precept: 20, temper: -25 }],
		['Let it go to whoever it is already down for.', { ambition: -50, precept: 40, defiance: -35 }]
	]),

	// ================================================================ TEMPER
	q('ink-across-the-parchment', 'short', 'temper', 'temper', 'Somebody knocks the ink across the parchment you have worked on all week, on purpose, and your wand is already in your hand.', [
		['Fire it off before you have decided to.', { temper: 90, precept: -50, ambition: -20 }],
		['Put the wand away and start over.', { temper: -85, precept: 40, candour: -20, reckoning: -30 }],
		['Speak instead, wandless.', { temper: 55, candour: 75, defiance: 20, reckoning: 30 }],
		['Walk out and leave the mess for later.', { temper: -40, attachment: -30, defiance: -25 }]
	]),
	q('reaching-for-the-fire', 'medium', 'temper', 'temper', 'Your plate is taken away and spilled down your sleeve after the exam goes wrong, and whatever dropped it is already reaching for the fire.', [
		['Catch its wrist before the fire does.', { temper: -60, attachment: 55, precept: -20, reckoning: -40 }],
		['Snap at it, and let it reach the fire anyway.', { temper: 70, attachment: -55, reckoning: 20 }],
		['Order it to stop, now.', { temper: -55, precept: 35, attachment: 20, reckoning: -30 }],
		['Walk out, and leave it to whatever it decides.', { temper: -65, attachment: -50, precept: -20 }]
	]),
	q('word-for-word', 'long', 'temper', 'temper', 'The portrait outside the staffroom is retelling, word for word, what you called the caretaker last night, and he has stopped to listen.', [
		['Own it, to his face, right now.', { temper: 40, candour: 55, attachment: -20 }],
		['Tell the portrait to stop.', { temper: -35, defiance: 30, candour: -20 }],
		['Wait until he has gone, then ask what it heard.', { temper: -45, precept: 30, candour: -35, attachment: -35 }],
		['Say it again, louder, so no version but yours stands.', { temper: 55, candour: 50, defiance: 45 }]
	]),
	q('half-out-of-your-wand', 'long', 'temper', 'temper', 'Somebody on the staircase repeats what they have decided about your family, louder this time, and the jinx that ends it is half out of your wand.', [
		['Cast it. Deal with the trace after.', { temper: 55, candour: 30, precept: -35, reckoning: 30 }],
		['Pocket the wand and take the long way round.', { temper: -50, defiance: -30, precept: 20, reckoning: -30 }],
		['Hex the banister instead, in front of them.', { temper: 30, candour: 20, defiance: 35 }],
		['Stay quiet and let them run out of things to say.', { temper: -35, precept: 25, attachment: -20 }]
	]),
];
